refactor: dto, entity, model in domain directory

diff --git a/hack/swipe b/hack/swipe
--- a/hack/swipe
+++ b/hack/swipe
@@ -1,17 +1,22 @@
 #!/usr/bin/env bash
 
-ISFLAG=false
+# a : Duc Hung Ho @kyeranyo
+# e : <hunghd.dev@gmail.com>
+# bash scripts cli for swipe core api server
 
-# Function to display help
+# function to display help
 show_help() {
     echo "Usage: $(basename $0) [command] [options]"
     echo "Usage: $(basename $0) [options]"
     echo
     echo "Options:"
-    echo "  -h, --help          Show this help message and exit"
+    echo "  -h, --help              Show this help message and exit"
     echo "Command:"
-    echo "  run                 Run swipe with options"
-    echo "  docker              Interact with swipe docker image"
+    echo "  i, install              Install dependencies for swipe"
+    echo "  run                     Run swipe in dev mode with options"
+    echo "  start                   Start swipe"
+    echo "  build                   Build swipe binary file"
+    echo "  docker                  Interact with swipe docker image"
     echo
 }
 
@@ -61,13 +66,15 @@ function docker_command() {
 
 function run_command() {
     run_show_help(){
-        echo "Usage: $(basename $0) docker [options]"
+        echo "Usage: $(basename $0) run [options]"
         echo
         echo "Options:"
-        echo "  -h, --help                              Show this help message and exit"
-        echo "  -g, --greet NAME                        Display a greeting message to NAME"
-        echo "  -t, --test  NAME                        Run unit test the module"
-        echo "  -d, --dash  REDIS:URI REDIS:PASSWORD    Connect to task worker dashboard"
+        echo "  -h, --help                               Show this help message and exit"
+        echo "  -g, --greet  NAME                        Display a greeting message to NAME"
+        echo "  -t, --test   NAME                        Run unit test the module"
+        echo "  -d, --dash   REDIS:URI REDIS:PASSWORD    Connect to task worker dashboard"
+        echo "  -s, --server                             Run core api server"
+        echo "  -w, --worker                             Run worker of core api server"
         echo
     }
 
@@ -76,6 +83,14 @@ function run_command() {
             echo "Hello, $NAME!"
         fi
         exit 0
+    }
+
+    worker() {
+        go run ./cmd/main.go s
+    }
+
+    server() {
+        go run ./cmd/main.go w
     }
 
     test(){
@@ -149,15 +164,71 @@ function run_command() {
             -d|--dash)
                 dash
                 ;;
+            -s|--server)
+                server
+                ;;
+            -w|--worker)
+                worker
+                ;;
             *)
                 echo "Unknown option: $1" >&2
-                docker_show_help
+                run_show_help
                 exit 1
                 ;;
         esac
         shift
     done
     
+    exit 0
+}
+
+function start_command() {
+    start_show_help() {
+        echo "Usage: $(basename $0) start [options]"
+        echo
+        echo "Options:"
+        echo "  -h, --help                               Show this help message and exit"
+        echo "  -s, --server                             Run core api server"
+        echo "  -w, --worker                             Run worker of core api server"
+        echo
+    }
+
+    if [ -e [./bin/swipe] ]; then
+        echo "Binary file not found, please run 'bash hack/swipe build' to build binary file"
+        exit 1
+    fi
+
+    while [[ "$#" -gt 0 ]]; do
+        case $1 in
+            -h|--help)
+                start_show_help
+                exit 0
+                ;;
+            -s|--server)
+                ./bin/swipe s
+                exit 0
+                ;;
+            -w|--worker)
+                ./bin/swipe w
+                exit 0
+                ;;
+            *)
+                echo "Unknown option: $1" >&2
+                start_show_help
+                exit 1
+                ;;
+        esac
+        shift
+    done
+    
+    exit 0
+
+}
+
+function build_command {
+    echo "Building swipe binary file ..."
+    go build -ldflags="-s -w" -o ./bin/swipe ./cmd
+    echo "done"
     exit 0
 }
 
@@ -171,9 +242,20 @@ case $command in
         shift
         run_command "$@"
     ;;
+    start)
+        shift
+        start_command "$@"
+    ;;
+    build)
+        shift
+        build_command "$@"
+    ;;
+    i|install)
+        go mod download
+        exit 0
+    ;;
     *)
 esac
-
 
 # Parse command line arguments
 while [[ "$#" -gt 0 ]]; do
